{% set version = "1.1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-glmmml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/glmmML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/glmmML/glmmML_{{ version }}.tar.gz
  sha256: 2710f56530de37a52a042645da76c8af075d66e04eaee9e18bf1e5f32f0b7958

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - libblas
    - libcblas
  run:
    - r-base

test:
  commands:
    - $R -e "library('glmmML')"           # [not win]
    - "\"%R%\" -e \"library('glmmML')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=glmmML
  license: GPL-3.0-or-later
  summary: Binomial and Poisson regression for clustered data, fixed and random effects with bootstrapping.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - izahn
    - conda-forge/r
